### ISSUE TITLE
GPSTrackingBLL.dll class library code

### ISSUE THREAD

**Issue by nirajdhiman123** [khopaderahul01/vehicletracking#7]
can u help me with GPSTrackingBLL.dll class library code

**Comment by nirajdhiman123** [comment]
hi plz help with the GPSTrackingBLL.dll so with the help of that code i would be able to add the values in all the tables ......plz help is vry urgent

**Comment by nishant0123** [comment]
hey bro, can you please explain GPSTrackingBLL.dll library or can you provide me its source code. 
thankyou.
And thanks for the db.

**Comment by nitin-s81** [comment]
hello, nice of you to share such a useful project !
can you plz share source for GPS.dll, GPSTracking.dll and GPSTrackingBLL.dll ??

OR kindly tell the other way out so that I can modify / add new needed things.
many thanks in advance brother, and kindly, atleast, revert.

**Comment by nitin-s81** [comment]
I managed to do some dummy entries and add multiple logins. 
Getting exception , plz have a look : 
"An exception of type 'System.IndexOutOfRangeException' occurred in GPS.dll but was not handled in user code"

I again request to share the source for the already mentioned Dll's. It would be easier to work further in it ONLY IF u can do so.
email id : er_nitin.sharma@yahoo.co.in
thanks again

**Comment by zoro111** [comment]
hi, i am not the developer of the is project. you could contact the developer. thank you.
--------------------------------------------
On Mon, 4/30/18, nitin-s81 <notifications@github.com> wrote:

 Subject: Re: [khopaderahul01/vehicletracking] GPSTrackingBLL.dll class library code (#7)
 To: "khopaderahul01/vehicletracking" <vehicletracking@noreply.github.com>
 Cc: "Subscribed" <subscribed@noreply.github.com>
 Received: Monday, April 30, 2018, 3:10 AM
 
 hello, nice of you to share such
 a useful project !
 
 can you plz share source for GPS.dll, GPSTracking.dll and
 GPSTrackingBLL.dll ??
 OR kindly tell the other way out so that I can modify /
 add new needed things.
 
 many thanks in advance brother, and kindly, atleast,
 revert.
 
 —
 You are
 receiving this because you are subscribed to this thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by khopaderahul01** [comment]
Hi All,

GPSTrackingBLL is dll used in our project for hardware communication so you have to create your own dll for your hardware.

**Comment by vamshikrishna2407** [comment]
please give some steps to run this project
